version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - cd codebuild/ecr
      - ls
      - echo Build started on `date`
      - docker build --tag ${tag}:latest .
      - docker tag $tag:latest $ecr:$tag
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing image to ECR...
      - docker push $ecr:latest
      - docker push $ecr:$tag
      - 'printf "[{\\"name\\":\\"${tag}\\",\\"imageUri\\":\\"${ecr}:latest\\"}]" > imagedefinitions.json'
artifacts:
  files:
    - imagedefinitions.json
