version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g aws-cdk
      - pip3 install -r requirements.txt
  build:
    commands:
      - cd codebuild/ecs/cdk
      - cdk deploy --require-approval never -O out.json
      - python3 post_cdk_deployment.py